export const FONT_LIBRARY = [
  "Arial", "Arial Black", "Arial Narrow", "Arial Nova", "Arial Rounded MT",
  "Arial Unicode MS", "Abadi MT", "Agency FB", "Aharoni Bold", "Aldhabi",
  "Algerian", "Almanac MT", "American Uncial", "Andale Mono", "Andalus",
  "Andy", "Angsana New", "AngsanaUPC", "Aparajita", "Aptos",
  "Arabic Transparent", "Arabic Typesetting", "Arial Narrow Special", "Arial Special", "Augsburger Initials",
  "Avenir Next LT Pro", "Bahnschrift", "Baskerville Old Face", "Batang & BatangChe", "Bauhaus 93",
  "Beesknees ITC", "Bell MT", "Bembo", "Berlin Sans FB", "Bernard MT Condensed",
  "Bickley Script", "Biome", "BIZ UDGothic", "BIZ UDMincho Medium", "Blackadder ITC",
  "Bodoni MT", "Bodoni MT Condensed", "Bon Apetit MT", "Book Antiqua", "Bookman Old Style",
  "Bookshelf Symbol", "Bradley Hand ITC", "Braggadocio", "BriemScript", "Britannic Bold",
  "Broadway", "Browallia New", "BrowalliaUPC", "Brush Script MT", "Calibri",
  "Californian FB", "Calisto MT", "Cambria", "Candara", "Cariadings",
  "Castellar", "Cavolini", "Centaur", "Century", "Century Gothic",
  "Century Schoolbook", "Chiller", "Colonna MT", "Comic Sans MS", "Consolas",
  "Constantia", "Contemporary Brush", "Cooper Black", "Copperplate Gothic", "Corbel",
  "Cordia New", "CordiaUPC", "Courier New", "Curlz MT", "Dante",
  "DaunPenh", "David", "Daytona", "Desdemona", "DFKai-SB",
  "DilleniaUPC", "Directions MT", "DokChampa", "Dotum & DotumChe", "Ebrima",
  "Eckmann", "Edda", "Edwardian Script ITC", "Elephant", "Engravers MT",
  "Enviro", "Eras ITC", "Estrangelo Edessa", "EucrosiaUPC", "Euphemia",
  "Eurostile", "FangSong", "Felix Titling", "Fine Hand", "Fixed Miriam Transparent",
  "Flexure", "Footlight MT", "Forte", "Franklin Gothic", "Franklin Gothic Medium",
  "FrankRuehl", "FreesiaUPC", "Freestyle Script", "French Script MT", "Futura",
  "Gabriola", "Gadugi", "Garamond", "Garamond MT", "Gautami",
  "Georgia", "Georgia Ref", "Gigi", "Gill Sans MT", "Gill Sans MT Condensed",
  "Gisha", "Gloucester", "Goudy Old Style", "Goudy Stout", "Gradl",
  "Grotesque", "Gulim & GulimChe", "Gungsuh & GungsuhChe", "Hadassah Friedlaender", "Haettenschweiler",
  "Harlow Solid Italic", "Harrington", "HGGothicE", "HGMinchoE", "HGSoeiKakugothicUB",
  "High Tower Text", "Holidays MT", "HoloLens MDL2 Assets", "Impact", "Imprint MT Shadow",
  "Informal Roman", "IrisUPC", "Iskoola Pota", "JasmineUPC", "Javanese Text",
  "Jokerman", "Juice ITC", "KaiTi", "Kalinga", "Kartika",
  "Keystrokes MT", "Khmer UI", "Kigelia", "Kino MT", "KodchiangUPC",
  "Kokila", "Kristen ITC", "Kunstler Script", "Lao UI", "Latha",
  "LCD", "Leelawadee", "Levenim MT", "LilyUPC", "Lucida Blackletter",
  "Lucida Bright", "Lucida Bright Math", "Lucida Calligraphy", "Lucida Console", "Lucida Fax",
  "Lucida Handwriting", "Lucida Sans", "Lucida Sans Typewriter", "Lucida Sans Unicode", "Magneto",
  "Maiandra GD", "Malgun Gothic", "Mangal", "Map Symbols", "Marlett",
  "Matisse ITC", "Matura MT Script Capitals", "McZee", "Mead Bold", "Meiryo",
  "Mercurius Script MT Bold", "Microsoft GothicNeo", "Microsoft Himalaya", "Microsoft JhengHei", "Microsoft JhengHei UI",
  "Microsoft New Tai Lue", "Microsoft PhagsPa", "Microsoft Sans Serif", "Microsoft Tai Le", "Microsoft Uighur",
  "Microsoft YaHei", "Microsoft YaHei UI", "Microsoft Yi Baiti", "MingLiU", "MingLiU-ExtB",
  "MingLiU_HKSCS", "MingLiU_HKSCS-ExtB", "Minion Web", "Miriam", "Miriam Fixed",
  "Mistral", "Modern Love", "Modern No. 20", "Mongolian Baiti", "Monotype.com",
  "Monotype Corsiva", "Monotype Sorts", "MoolBoran", "MS Gothic", "MS LineDraw",
  "MS Mincho", "MS Outlook", "MS PMincho", "MS Reference", "MT Extra",
  "MV Boli", "Myanmar Text", "Narkisim", "News Gothic MT", "New Caledonia",
  "Niagara", "Nirmala UI", "NSimSun", "Nyala", "OCR A Extended",
  "OCR-B-Digits", "OCRB", "Old English Text MT", "Onyx", "Palace Script MT",
  "Palatino Linotype", "Papyrus", "Parade", "Parchment", "Parties MT",
  "Peignot Medium", "Pepita MT", "Perpetua", "Perpetua Titling MT", "Placard Condensed",
  "Plantagenet Cherokee", "Playbill", "PMingLiU", "PMingLiU-ExtB", "Poor Richard",
  "Posterama", "Pristina", "Quire Sans", "Raavi", "Rage Italic",
  "Ransom", "Ravie", "RefSpecialty", "Rockwell", "Rockwell Nova",
  "Rod", "Runic MT Condensed", "Sabon Next LT", "Sagona", "Sakkal Majalla",
  "Script MT Bold", "Segoe Chess", "Segoe Print", "Segoe Script", "Segoe UI",
  "Segoe UI Symbol", "Selawik", "Shonar Bangla", "Showcard Gothic", "Shruti",
  "Signs MT", "SimHei", "Simplified Arabic Fixed", "SimSun", "SimSun-ExtB",
  "Sitka", "Skeena Indigenous", "Snap ITC", "Sports MT", "STCaiyun",
  "Stencil", "STFangsong", "STHupo", "STKaiti", "Stop",
  "STXihei", "STXingkai", "STXinwei", "STZhongsong", "Sylfaen",
  "Symbol", "Tahoma", "Tempo Grunge", "Temp Installer Font", "Tempus Sans ITC",
  "The Hand", "The Serif Hand", "Times New Roman", "Times New Roman Special", "Tisa Offc Serif Pro",
  "Traditional Arabic", "Transport MT", "Trebuchet MS", "Tunga", "Tw Cen MT",
  "Univers", "Urdu Typesetting", "Utsaah", "Vacation MT", "Vani",
  "Verdana", "Verdana Ref", "Vijaya", "Viner Hand ITC", "Vivaldi",
  "Vixar ASCI", "Vladimir Script", "Vrinda", "Walbaum", "Webdings",
  "Westminster", "Wide Latin", "Wingdings", "Abadi MT Condensed Light", "Albertus Extra Bold",
  "Albertus Medium", "Antique Olive", "Arial MT", "Bazooka", "Boulder",
  "Calligrapher", "Cezanne", "CG Omega", "CG Times", "Charlesworth",
  "Chaucer", "Clarendon Condensed", "Copperplate Gothic Bold", "Copperplate Gothic Light", "Cornerstone",
  "Coronet", "Courier", "Cuckoo", "Dauphin", "Denmark",
  "Fransiscan", "Geneva", "Heather", "Helvetica", "Herald",
  "Jester", "Letter Gothic", "Lithograph", "Lithograph Light", "Long Island",
  "Marigold", "Market", "News GothicMT", "Old Century", "Pegasus",
  "Pickwick", "Poster", "Pythagoras", "Sceptre", "Sherwood",
  "Signboard", "Socket", "Steamer", "Storybook", "Subway",
  "Technical", "Teletype", "Times", "Times New Roman PS", "Tristan",
  "Tubular", "Unicorn", "Univers Condensed", "Vagabond", "Allegro",
  "Amazone BT", "AmerType Md BT", "Arrus BT", "Aurora Cn BT", "AvantGarde Bk BT",
  "AvantGarde Md BT", "BankGothic Md BT", "Benguiat Bk BT", "BernhardFashion BT", "BernhardMod BT",
  "BinnerD", "Bremen Bd BT", "CaslonOpnface BT", "Charter Bd BT", "Charter BT",
  "ChelthmITC Bk BT", "CloisterBlack BT", "CopperplGoth Bd BT", "English 111 Vivace BT", "EngraversGothic BT",
  "Exotc350 Bd BT", "Freefrm721 Blk BT", "FrnkGothITC Bk BT", "Futura Bk BT", "Futura Lt BT",
  "Futura Md BT", "Futura ZBlk BT", "FuturaBlack BT", "Galliard BT", "Geometr231 BT",
  "Geometr231 Hv BT", "Geometr231 Lt BT", "GeoSlab 703 Lt BT", "GeoSlab 703 XBd BT", "GoudyHandtooled BT",
  "GoudyOLSt BT", "Humanst521 BT", "Humanst 521 Cn BT", "Humanst521 Lt BT", "Incised901 Bd BT",
  "Incised901 BT", "Incised901 Lt BT", "Informal011 BT", "Kabel Bk BT", "Kabel Ult BT",
  "Kaufmann Bd BT", "Kaufmann BT", "Korinna BT", "Lydian BT", "NewsGoth BT",
  "Onyx BT", "OzHandicraft BT", "PosterBodoni BT", "PTBarnum BT", "Ribbon131 Bd BT",
  "Serifa BT", "Serifa Th BT", "ShelleyVolante BT", "Souvenir Lt BT", "Staccato222 BT",
  "Swis721 BlkEx BT", "Swiss911 XCm BT", "TypoUpright BT", "ZapfEllipt BT", "ZapfHumnst BT",
  "ZapfHumnst Dm BT", "Zurich BlkEx BT", "Zurich Ex BT", "monospace", "serif",
] as const;
